---
- hosts: all
  ignore_unreachable: yes
  ignore_errors: yes
  gather_facts: no
  serial: yes
  become: yes

  tasks:
  - name: Add group <groupname>
    ansible.builtin.group:
      name: <groupname>
      gid: <group-id>

  - name: Add user <username>
    ansible.builtin.user:
      name: <username>
      comment: <user-comment>
      group: <groupname>
      shell: /bin/bash
      uid: <user-ID>

  # below requires ansible.posix
  # install with "ansible-galaxy collection install ansible.posix"
  - name: Add pub sshkey <username>
    ansible.posix.authorized_key:
      user: <username>
      state: present
      key: "{{ lookup('file', '<username>-sshkey.pub') }}"
...
